config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :ben_key_project_finance_forms
  resources :ben_overall_project_finance_forms
  resources :glitch_input_forms
  resources :ben_update_forms
  resources :ben_user_update_forms
  resources :ben_investor_update_forms
  resources :ben_management_update_forms
  resources :ben_selection_forms
  resources :ben_new_project_forms
  resources :ben_available_frontstage_forms
  resources :ben_available_backstage_forms
  resources :resignation_forms
  resources :complaint_forms
  resources :transfer_forms
  resources :management_review_forms
  resources :management_request_forms
  resources :management_applicant_forms
  resources :investor_sponsor_forms
  resources :investor_support_forms
  resources :investor_company_forms
  resources :artist_applicant_forms
  resources :crew_applicant_forms
  resources :musician_applicant_forms
  resources :actor_applicant_forms
  resources :information_forms
  devise_for :bens, controllers: {registrations: "bens/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :investors, controllers: {registrations: "investors/registrations"}
  devise_for :managements, controllers: { registrations: "managements/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete "/logout", to: "sessions#destroy"

  get '/ben_key_project_finance_forms', to: 'ben_key_project_finance_forms#index', as: :key_project_finance
  get '/ben_overall_project_finance_forms', to: 'ben_overall_project_finance_forms#index', as: :overall_project_finance
  get '/glitch_input_forms', to: 'glitch_input_forms#index', as: :glitch_form
  get '/ben_update_forms', to: 'ben_update_forms#index', as: :primary_update
  get '/ben_user_update_forms', to: 'ben_user_update_forms#index', as: :user_update
  get '/ben_investor_update_forms', to: 'ben_investor_update_forms#index', as: :investor_update
  get '/ben_management_update_forms', to: 'ben_management_forms#index', as: :management_update
  get '/ben_selection_forms', to: 'ben_selection_forms#index', as: :bens_selection
  get '/ben_new_project_forms', to: 'ben_new_project_forms#index', as: :new_project_form
  get '/ben_available_frontstage_forms', to: 'ben_available_frontstage_forms#index', as: :available_frontstage
  get '/ben_available_backstage_forms', to: 'ben_available_backstage_forms#index', as: :available_backstage
  get '/actor_applicant_forms', to: 'actor_applicant_forms#index', as: :actor_applicant
  get '/artist_applicant_forms', to: 'artist_applicant_forms#index', as: :artist_applicant
  get '/crew_applicant_form', to: 'crew_applicant_forms#index', as: :crew_applicant
  get '/information_forms', to: 'information_forms#index', as: :form_of_information
  get '/investor_company_forms', to: 'investor_company_forms#index', as: :company_info
  get '/investor_sponsor_forms', to: 'investor_sponsor_forms#index', as: :sponsor_form
  get '/investor_support_forms', to: 'investor_support_forms#index', as: :support_form
  get '/musician_applicant_forms', to: 'musician_applicant_forms#index', as: :musician_form
  get '/management_applicant_forms', to: 'management_applicant_forms#index', as: :management_applicant
  get '/management_request_forms', to: 'management_request_forms#index', as: :management_request
  get '/management_review_forms', to: 'management_review_forms#index', as: :management_review
  get '/transfer_forms', to: 'transfer_forms#index', as: :form_transfer
  get '/complaint_forms', to: 'complaint_forms#index', as: :form_complaint
  get '/resignation_form', to: 'resignation_forms#index', as: :form_resign

  post "users/signup", to: "users#create"
  post "investors/signup", to: "investors#create"
  post "managements/signup", to: "managements#create"
  post "bens/signup", to: "bens#create"
  post "users/login", to: "sessions#create"
  post "bens/login", to: "sessions#create"
  post "managements/login", to: "sessions#create"
  post "investors/login", to: "sessions#create"
  get "users/sign_out", to: "sessions#destroy"
  get "bens/sign_out", to: "sessions#destroy"
  get "managements/sign_out", to: "sessions#destroy"
  get "investors/sign_out", to: "sessions#destroy"
  get "about", to: "pages#about", as: :about
  get 'bens' => 'ben#primary', as: :ben_root
  get 'users' => 'users#primary', as: :user_root
  get 'investors' => 'investors#primary', as: :investor_root
  get 'managements' => 'managements#primary', as: :management_root


end

app/controllers/ben_management_update_forms_controller.rb
class BenManagementUpdateFormsController < ApplicationController
  before_action :set_ben_management_update_form, only: %i[ show edit update destroy ]

  # GET /ben_management_update_forms or /ben_management_update_forms.json
  def index
    @ben_management_update_forms = BenManagementUpdateForm.all
  end

  # GET /ben_management_update_forms/1 or /ben_management_update_forms/1.json
  def show
  end

  # GET /ben_management_update_forms/new
  def new
    @ben_management_update_form = BenManagementUpdateForm.new
  end

  # GET /ben_management_update_forms/1/edit
  def edit
  end

  # POST /ben_management_update_forms or /ben_management_update_forms.json
  def create
    @ben_management_update_form = BenManagementUpdateForm.new(ben_management_update_form_params)
    @ben_management_update_form.ben = current_user

    respond_to do |format|
      if @ben_management_update_form.save
        format.html { redirect_to ben_management_update_form_url(@ben_management_update_form), notice: "Ben management update form was successfully created." }
        format.json { render :show, status: :created, location: @ben_management_update_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ben_management_update_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ben_management_update_forms/1 or /ben_management_update_forms/1.json
  def update
    respond_to do |format|
      if @ben_management_update_form.update(ben_management_update_form_params)
        format.html { redirect_to ben_management_update_form_url(@ben_management_update_form), notice: "Ben management update form was successfully updated." }
        format.json { render :show, status: :ok, location: @ben_management_update_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ben_management_update_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ben_management_update_forms/1 or /ben_management_update_forms/1.json
  def destroy
    @ben_management_update_form.destroy

    respond_to do |format|
      format.html { redirect_to ben_management_update_forms_url, notice: "Ben management update form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ben_management_update_form
      @ben_management_update_form = BenManagementUpdateForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ben_management_update_form_params
      params.require(:ben_management_update_form).permit(:update_title, :projects_involved, :update_description)
    end
end

app/views/ben_management_update_forms/_ben_management_update_form.html.erb
<div id="<%= dom_id ben_management_update_form %>">
  <p>
    <strong>Update title:</strong>
    <%= ben_management_update_form.update_title %>
  </p>

  <p>
    <strong>Projects involved:</strong>
    <%= ben_management_update_form.projects_involved %>
  </p>

  <p>
    <strong>Update description:</strong>
    <%= ben_management_update_form.update_description %>
  </p>

</div>

app/views/ben_management_update_forms/_form.html.erb
<%= simple_form_for(@ben_management_update_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :update_title %>
    <%= f.input :projects_involved %>
    <%= f.input :update_description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ben_management_update_forms/edit.html.erb
<h1>Editing ben management update form</h1>

<%= render "form", ben_management_update_form: @ben_management_update_form %>

<br>

<div>
  <%= link_to "Show this ben management update form", @ben_management_update_form %> |
  <%= link_to "Back to ben management update forms", ben_management_update_forms_path %>
</div>

app/views/ben_management_update_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ben management update forms</h1>

<div id="ben_management_update_forms">
  <% @ben_management_update_forms.each do |ben_management_update_form| %>
    <%= render ben_management_update_form %>
    <p>
      <%= link_to "Show this ben management update form", ben_management_update_form %>
    </p>
  <% end %>
</div>

<%= link_to "New ben management update form", new_ben_management_update_form_path %>
<%= link_to "Back to the main page", ben_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>

app/views/ben_management_update_forms/new.html.erb
<h1>New ben management update form</h1>

<%= render "form", ben_management_update_form: @ben_management_update_form %>

<br>

<div>
  <%= link_to "Back to ben management update forms", ben_management_update_forms_path %>
</div>

app/views/ben_management_update_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ben_management_update_form %>

<div>
  <%= link_to "Edit this ben management update form", edit_ben_management_update_form_path(@ben_management_update_form) %> |
  <%= link_to "Back to ben management update forms", ben_management_update_forms_path %>

  <%= button_to "Destroy this ben management update form", @ben_management_update_form, method: :delete %>
</div>