config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :ben_key_project_finance_forms
  resources :ben_overall_project_finance_forms
  resources :glitch_input_forms
  resources :ben_update_forms
  resources :ben_user_update_forms
  resources :ben_investor_update_forms
  resources :ben_management_update_forms
  resources :ben_selection_forms
  resources :ben_new_project_forms
  resources :ben_available_frontstage_forms
  resources :ben_available_backstage_forms
  resources :resignation_forms
  resources :complaint_forms
  resources :transfer_forms
  resources :management_review_forms
  resources :management_request_forms
  resources :management_applicant_forms
  resources :investor_sponsor_forms
  resources :investor_support_forms
  resources :investor_company_forms
  resources :artist_applicant_forms
  resources :crew_applicant_forms
  resources :musician_applicant_forms
  resources :actor_applicant_forms
  resources :information_forms
  devise_for :bens, controllers: {registrations: "bens/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :investors, controllers: {registrations: "investors/registrations"}
  devise_for :managements, controllers: { registrations: "managements/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete "/logout", to: "sessions#destroy"

  get '/ben_key_project_finance_forms', to: 'ben_key_project_finance_forms#index', as: :key_project_finance
  get '/ben_overall_project_finance_forms', to: 'ben_overall_project_finance_forms#index', as: :overall_project_finance
  get '/glitch_input_forms', to: 'glitch_input_forms#index', as: :glitch_form
  get '/ben_update_forms', to: 'ben_update_forms#index', as: :primary_update
  get '/ben_user_update_forms', to: 'ben_user_update_forms#index', as: :user_update
  get '/ben_investor_update_forms', to: 'ben_investor_update_forms#index', as: :investor_update
  get '/ben_management_update_forms', to: 'ben_management_forms#index', as: :management_update
  get '/ben_selection_forms', to: 'ben_selection_forms#index', as: :bens_selection
  get '/ben_new_project_forms', to: 'ben_new_project_forms#index', as: :new_project_form
  get '/ben_available_frontstage_forms', to: 'ben_available_frontstage_forms#index', as: :available_frontstage
  get '/ben_available_backstage_forms', to: 'ben_available_backstage_forms#index', as: :available_backstage
  get '/actor_applicant_forms', to: 'actor_applicant_forms#index', as: :actor_applicant
  get '/artist_applicant_forms', to: 'artist_applicant_forms#index', as: :artist_applicant
  get '/crew_applicant_form', to: 'crew_applicant_forms#index', as: :crew_applicant
  get '/information_forms', to: 'information_forms#index', as: :form_of_information
  get '/investor_company_forms', to: 'investor_company_forms#index', as: :company_info
  get '/investor_sponsor_forms', to: 'investor_sponsor_forms#index', as: :sponsor_form
  get '/investor_support_forms', to: 'investor_support_forms#index', as: :support_form
  get '/musician_applicant_forms', to: 'musician_applicant_forms#index', as: :musician_form
  get '/management_applicant_forms', to: 'management_applicant_forms#index', as: :management_applicant
  get '/management_request_forms', to: 'management_request_forms#index', as: :management_request
  get '/management_review_forms', to: 'management_review_forms#index', as: :management_review
  get '/transfer_forms', to: 'transfer_forms#index', as: :form_transfer
  get '/complaint_forms', to: 'complaint_forms#index', as: :form_complaint
  get '/resignation_form', to: 'resignation_forms#index', as: :form_resign

  post "users/signup", to: "users#create"
  post "investors/signup", to: "investors#create"
  post "managements/signup", to: "managements#create"
  post "bens/signup", to: "bens#create"
  post "users/login", to: "sessions#create"
  post "bens/login", to: "sessions#create"
  post "managements/login", to: "sessions#create"
  post "investors/login", to: "sessions#create"
  get "users/sign_out", to: "sessions#destroy"
  get "bens/sign_out", to: "sessions#destroy"
  get "managements/sign_out", to: "sessions#destroy"
  get "investors/sign_out", to: "sessions#destroy"
  get "about", to: "pages#about", as: :about
  get 'bens' => 'ben#primary', as: :ben_root
  get 'users' => 'users#primary', as: :user_root
  get 'investors' => 'investors#primary', as: :investor_root
  get 'managements' => 'managements#primary', as: :management_root


end

app/controllers/management_applicant_forms_controller.rb
class ManagementApplicantFormsController < ApplicationController
  before_action :set_management_applicant_form, only: %i[ show edit update destroy ]

  # GET /management_applicant_forms or /management_applicant_forms.json
  def index
    @management_applicant_forms = InvestorSponsorForm.all
  end

  # GET /management_applicant_forms/1 or /management_applicant_forms/1.json
  def show
    if current_user.management?
      @management_applicant_forms = ManagementApplicantForm.all
    else
      @management_applicant_forms = ManagementApplicantForm.where(user: current_user)
    end
  end

  # GET /management_applicant_forms/new
  def new
    @management_applicant_form = ManagementApplicantForm.new
  end

  # GET /management_applicant_forms/1/edit
  def edit
  end

  # POST /management_applicant_forms or /management_applicant_forms.json
  def create
    @management_applicant_form = ManagementApplicantForm.new(management_applicant_form_params)
    @management_applicant_form.management = current_user

    respond_to do |format|
      if @management_applicant_form.save
        format.html { redirect_to management_applicant_form_url(@management_applicant_form), notice: "Management applicant form was successfully created." }
        format.json { render :show, status: :created, location: @management_applicant_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @management_applicant_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /management_applicant_forms/1 or /management_applicant_forms/1.json
  def update
    respond_to do |format|
      if @management_applicant_form.update(management_applicant_form_params)
        format.html { redirect_to management_applicant_form_url(@management_applicant_form), notice: "Management applicant form was successfully updated." }
        format.json { render :show, status: :ok, location: @management_applicant_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @management_applicant_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /management_applicant_forms/1 or /management_applicant_forms/1.json
  def destroy
    @management_applicant_form.destroy

    respond_to do |format|
      format.html { redirect_to management_applicant_forms_url, notice: "Management applicant form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management_applicant_form
      @management_applicant_form = ManagementApplicantForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def management_applicant_form_params
      params.require(:management_applicant_form).permit(:preferred_project, :management_roles, :interest_reason, :availability)
    end
end

app/views/management_applicant_forms/_form.html.erb
<%= simple_form_for(@management_applicant_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :preferred_project %>
    <%= f.input :management_roles %>
    <%= f.input :interest_reason %>
    <%= f.input :availability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/management_applicant_forms/_management_applicant_form.html.erb
<div id="<%= dom_id management_applicant_form %>">
  <p>
    <strong>Preferred project:</strong>
    <%= management_applicant_form.preferred_project %>
  </p>

  <p>
    <strong>Management roles:</strong>
    <%= management_applicant_form.management_roles %>
  </p>

  <p>
    <strong>Interest reason:</strong>
    <%= management_applicant_form.interest_reason %>
  </p>

  <p>
    <strong>Availability:</strong>
    <%= management_applicant_form.availability %>
  </p>

</div>

app/views/management_applicant_forms/edit.html.erb
<h1>Editing management applicant form</h1>

<%= render "form", management_applicant_form: @management_applicant_form %>

<br>

<div>
  <%= link_to "Show this management applicant form", @management_applicant_form %> |
  <%= link_to "Back to management applicant forms", management_applicant_forms_path %>
</div>

app/views/management_applicant_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Management applicant forms</h1>

<div id="management_applicant_forms">
  <% @management_applicant_forms.each do |management_applicant_form| %>
    <%= render management_applicant_form %>
    <p>
      <%= link_to "Show this management applicant form", management_applicant_form %>
    </p>
  <% end %>
</div>

<%= link_to "New management applicant form", new_management_applicant_form_path %>
<%= link_to "Back to the main page", management_registration_url, class: "btn btn-pink text-grey text-uppercase rounded-pill fw-bold" %>

app/views/management_applicant_forms/new.html.erb
<h1>New management applicant form</h1>

<%= render "form", management_applicant_form: @management_applicant_form %>

<br>

<div>
  <%= link_to "Back to management applicant forms", management_applicant_forms_path %>
</div>

app/views/management_applicant_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @management_applicant_form %>

<div>
  <%= link_to "Edit this management applicant form", edit_management_applicant_form_path(@management_applicant_form) %> |
  <%= link_to "Back to management applicant forms", management_applicant_forms_path %>

  <%= button_to "Destroy this management applicant form", @management_applicant_form, method: :delete %>
</div>