config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :ben_key_project_finance_forms
  resources :ben_overall_project_finance_forms
  resources :glitch_input_forms
  resources :ben_update_forms
  resources :ben_user_update_forms
  resources :ben_investor_update_forms
  resources :ben_management_update_forms
  resources :ben_selection_forms
  resources :ben_new_project_forms
  resources :ben_available_frontstage_forms
  resources :ben_available_backstage_forms
  resources :resignation_forms
  resources :complaint_forms
  resources :transfer_forms
  resources :management_review_forms
  resources :management_request_forms
  resources :management_applicant_forms
  resources :investor_sponsor_forms
  resources :investor_support_forms
  resources :investor_company_forms
  resources :artist_applicant_forms
  resources :crew_applicant_forms
  resources :musician_applicant_forms
  resources :actor_applicant_forms
  resources :information_forms
  devise_for :bens, controllers: {registrations: "bens/registrations"}
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :investors, controllers: {registrations: "investors/registrations"}
  devise_for :managements, controllers: { registrations: "managements/registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  delete "/logout", to: "sessions#destroy"

  get '/ben_key_project_finance_forms', to: 'ben_key_project_finance_forms#index', as: :key_project_finance
  get '/ben_overall_project_finance_forms', to: 'ben_overall_project_finance_forms#index', as: :overall_project_finance
  get '/glitch_input_forms', to: 'glitch_input_forms#index', as: :glitch_form
  get '/ben_update_forms', to: 'ben_update_forms#index', as: :primary_update
  get '/ben_user_update_forms', to: 'ben_user_update_forms#index', as: :user_update
  get '/ben_investor_update_forms', to: 'ben_investor_update_forms#index', as: :investor_update
  get '/ben_management_update_forms', to: 'ben_management_forms#index', as: :management_update
  get '/ben_selection_forms', to: 'ben_selection_forms#index', as: :bens_selection
  get '/ben_new_project_forms', to: 'ben_new_project_forms#index', as: :new_project_form
  get '/ben_available_frontstage_forms', to: 'ben_available_frontstage_forms#index', as: :available_frontstage
  get '/ben_available_backstage_forms', to: 'ben_available_backstage_forms#index', as: :available_backstage
  get '/actor_applicant_forms', to: 'actor_applicant_forms#index', as: :actor_applicant
  get '/artist_applicant_forms', to: 'artist_applicant_forms#index', as: :artist_applicant
  get '/crew_applicant_form', to: 'crew_applicant_forms#index', as: :crew_applicant
  get '/information_forms', to: 'information_forms#index', as: :form_of_information
  get '/investor_company_forms', to: 'investor_company_forms#index', as: :company_info
  get '/investor_sponsor_forms', to: 'investor_sponsor_forms#index', as: :sponsor_form
  get '/investor_support_forms', to: 'investor_support_forms#index', as: :support_form
  get '/musician_applicant_forms', to: 'musician_applicant_forms#index', as: :musician_form
  get '/management_applicant_forms', to: 'management_applicant_forms#index', as: :management_applicant
  get '/management_request_forms', to: 'management_request_forms#index', as: :management_request
  get '/management_review_forms', to: 'management_review_forms#index', as: :management_review
  get '/transfer_forms', to: 'transfer_forms#index', as: :form_transfer
  get '/complaint_forms', to: 'complaint_forms#index', as: :form_complaint
  get '/resignation_form', to: 'resignation_forms#index', as: :form_resign

  post "users/signup", to: "users#create"
  post "investors/signup", to: "investors#create"
  post "managements/signup", to: "managements#create"
  post "bens/signup", to: "bens#create"
  post "users/login", to: "sessions#create"
  post "bens/login", to: "sessions#create"
  post "managements/login", to: "sessions#create"
  post "investors/login", to: "sessions#create"
  get "users/sign_out", to: "sessions#destroy"
  get "bens/sign_out", to: "sessions#destroy"
  get "managements/sign_out", to: "sessions#destroy"
  get "investors/sign_out", to: "sessions#destroy"
  get "about", to: "pages#about", as: :about
  get 'bens' => 'ben#primary', as: :ben_root
  get 'users' => 'users#primary', as: :user_root
  get 'investors' => 'investors#primary', as: :investor_root
  get 'managements' => 'managements#primary', as: :management_root


end

app/controllers/transfer_forms_controller.rb
class TransferFormsController < ApplicationController
  before_action :set_transfer_form, only: %i[ show edit update destroy ]

  # GET /transfer_forms or /transfer_forms.json
  def index
    @transfer_forms = TransferForm.all
  end

  # GET /transfer_forms/1 or /transfer_forms/1.json
  def show
  end

  # GET /transfer_forms/new
  def new
    @transfer_form = TransferForm.new
  end

  # GET /transfer_forms/1/edit
  def edit
  end

  # POST /transfer_forms or /transfer_forms.json
  def create
    @transfer_form = TransferForm.new(transfer_form_params)

    respond_to do |format|
      if @transfer_form.save
        format.html { redirect_to transfer_form_url(@transfer_form), notice: "Transfer form was successfully created." }
        format.json { render :show, status: :created, location: @transfer_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transfer_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfer_forms/1 or /transfer_forms/1.json
  def update
    respond_to do |format|
      if @transfer_form.update(transfer_form_params)
        format.html { redirect_to transfer_form_url(@transfer_form), notice: "Transfer form was successfully updated." }
        format.json { render :show, status: :ok, location: @transfer_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transfer_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfer_forms/1 or /transfer_forms/1.json
  def destroy
    @transfer_form.destroy

    respond_to do |format|
      format.html { redirect_to transfer_forms_url, notice: "Transfer form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer_form
      @transfer_form = TransferForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transfer_form_params
      params.require(:transfer_form).permit(:transfer_from, :transfer_to, :project_involved, :transfer_reason, :outcome_expectation)
    end
end

app/views/transfer_forms/_form.html.erb
<%= simple_form_for(@transfer_form) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :transfer_from %>
    <%= f.input :transfer_to %>
    <%= f.input :project_involved %>
    <%= f.input :transfer_reason %>
    <%= f.input :outcome_expectation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transfer_forms/_transfer_form.html.erb
<div id="<%= dom_id transfer_form %>">
  <p>
    <strong>Transfer from:</strong>
    <%= transfer_form.transfer_from %>
  </p>

  <p>
    <strong>Transfer to:</strong>
    <%= transfer_form.transfer_to %>
  </p>

  <p>
    <strong>Project involved:</strong>
    <%= transfer_form.project_involved %>
  </p>

  <p>
    <strong>Transfer reason:</strong>
    <%= transfer_form.transfer_reason %>
  </p>

  <p>
    <strong>Outcome expectation:</strong>
    <%= transfer_form.outcome_expectation %>
  </p>

</div>

app/views/transfer_forms/edit.html.erb
<h1>Editing transfer form</h1>

<%= render "form", transfer_form: @transfer_form %>

<br>

<div>
  <%= link_to "Show this transfer form", @transfer_form %> |
  <%= link_to "Back to transfer forms", transfer_forms_path %>
</div>

app/views/transfer_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transfer forms</h1>

<div id="transfer_forms">
  <% @transfer_forms.each do |transfer_form| %>
    <%= render transfer_form %>
    <p>
      <%= link_to "Show this transfer form", transfer_form %>
    </p>
  <% end %>
</div>

<%= link_to "New transfer form", new_transfer_form_path %>

app/views/transfer_forms/new.html.erb
<h1>New transfer form</h1>

<%= render "form", transfer_form: @transfer_form %>

<br>

<div>
  <%= link_to "Back to transfer forms", transfer_forms_path %>
</div>

app/views/transfer_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transfer_form %>

<div>
  <%= link_to "Edit this transfer form", edit_transfer_form_path(@transfer_form) %> |
  <%= link_to "Back to transfer forms", transfer_forms_path %>

  <%= button_to "Destroy this transfer form", @transfer_form, method: :delete %>
</div>